var testCases = {
	"TC-1" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить сегодня в 6 вечера информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">\'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Добавить информацию:&nbsp;</h1><ul class="checkbox"><li id="c_c3tk">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id="c_d7ia">от <span style="color:red"><i>6 мая 2003 г.</i></span>&nbsp;</li><li id="c_d7ia">\'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>'         },

			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "06:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить вечера информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>от 6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>"  },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить сегодня информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>от 6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>" },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить сегодня вечера информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>от 6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>"  },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "06:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить сегодня вечера информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>от 6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>"  },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Добавить в 6 вечера информацию:&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_c3tk\">Структура БИК и порядок ведения справочника определена в Положении ЦБ РФ N 225-П&nbsp;</li></ul><ul><li id=\"c_d7ia\">от <span style=\"color:red\"><i>от 6 мая 2003 г.</i></span>&nbsp;</li><li id=\"c_d7ia\">'<b>О справочнике банковских идентификационных кодов участников расчетов</b>, осуществляющих платежи через расчетную сеть центрального банка Российской Федерации (Банка России)<br></li></ul></div>"      }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-2" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_gui6\"><b><i>Завтра </i></b>премьера фильма&nbsp;</li></ul><h1>Вчера вдоль дороги.&nbsp;</h1><p style=\"text-align: justify;\"><i>Вчера вдоль дороги</i> является&nbsp;</p><ol><li id=\"c_8hl8\"><span style=\"color:green\">самым дорогим фильмом в истории кинемотогрофа острова</span> <i>Панхуть</i>,&nbsp;</li><li id=\"c_8hl8\">с бюджетом <b>в 10 тысяч долларов</b>.&nbsp;</li></ol><p style=\"text-align: right;\"><b><i>Напомнить сходить.</i></b><br></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_gui6\"><b><i> </i></b>премьера фильма&nbsp;</li></ul><h1>Вчера вдоль дороги.&nbsp;</h1><p style=\"text-align: justify;\"><i>Вчера вдоль дороги</i> является&nbsp;</p><ol><li id=\"c_8hl8\"><span style=\"color:green\">самым дорогим фильмом в истории кинемотогрофа острова</span> <i>Панхуть</i>,&nbsp;</li><li id=\"c_8hl8\">с бюджетом <b>в 10 тысяч долларов</b>.&nbsp;</li></ol><p style=\"text-align: right;\"><b><i> сходить.</i></b><br></p></div>",   "event_alarms" : "0"  },

			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_gui6\"><b><i> </i></b>премьера фильма&nbsp;</li></ul><h1>Вчера вдоль дороги.&nbsp;</h1><p style=\"text-align: justify;\"><i>Вчера вдоль дороги</i> является&nbsp;</p><ol><li id=\"c_8hl8\"><span style=\"color:green\">самым дорогим фильмом в истории кинемотогрофа острова</span> <i>Панхуть</i>,&nbsp;</li><li id=\"c_8hl8\">с бюджетом <b>в 10 тысяч долларов</b>.&nbsp;</li></ol><p style=\"text-align: right;\"><b><i>Напомнить сходить.</i></b><br></p></div>"                }//ожидается рабочее время
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-3" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>День энергетика&nbsp;</h1><p style=\"text-align: justify;\">- это&nbsp;</p><ol><li id=\"c_lh0i\"><span style=\"color:blue\"><b><i>профессиональный праздни</i></b></span>к всех работников промышленности,&nbsp;</li><li id=\"c_lh0i\">охватывающей <i>выработку</i>,&nbsp;</li><li id=\"c_lh0i\"><i>передачу&nbsp;</i></li><li id=\"c_lh0i\">и <i>сбыт </i>потребителям электрической и тепловой энергии,&nbsp;</li></ol><p style=\"text-align: center;\">который они отмечают в один <b>из самых коротких световых дней</b> в году —&nbsp;</p><h1>22 декабря.<br></h1></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>День энергетика&nbsp;</h1><p style="text-align: justify;">- это&nbsp;</p><ol><li id="c_lh0i"><span style="color:blue"><b><i>профессиональный праздни</i></b></span>к всех работников промышленности,&nbsp;</li><li id="c_lh0i">охватывающей <i>выработку</i>,&nbsp;</li><li id="c_lh0i"><i>передачу&nbsp;</i></li><li id="c_lh0i">и <i>сбыт </i>потребителям электрической и тепловой энергии,&nbsp;</li></ol><p style="text-align: center;">который они отмечают в один <b>из самых коротких световых дней</b> в году —&nbsp;</p><h1>.<br></h1></div>' }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-4" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>22 дек — ПРАЙМ.&nbsp;</h1><ol><li id=\"c_ycpp\">Курс доллара поднялся выше<b> 56 рублей</b> на торгах <span style=\"color:red\"><i>Московской </i></span>биржи.&nbsp;</li><li id=\"c_ycpp\">Так, доллар достиг отметки <b>56,2 рубля</b>,&nbsp;</li></ol><ul><li id=\"c_4x9c\">тогда как ранее в ходе торгов он <span style=\"color:blue\">опускался</span> ниже отметки <b><i>55 рублей</i></b> за доллар.<br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1> — ПРАЙМ.&nbsp;</h1><ol><li id="c_ycpp">Курс доллара поднялся выше<b> 56 рублей</b> на торгах <span style="color:red"><i>Московской </i></span>биржи.&nbsp;</li><li id="c_ycpp">Так, доллар достиг отметки <b>56,2 рубля</b>,&nbsp;</li></ol><ul><li id="c_4x9c">тогда как ранее в ходе торгов он <span style="color:blue">опускался</span> ниже отметки <b><i>55 рублей</i></b> за доллар.<br></li></ul></div>' }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-5" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>02 апр 15 г&nbsp;</h1><p style=\"text-align: center;\"><span style=\"color:red\"><b><i>годовщина смерти Васи Пупкина.&nbsp;</i></b></span></p><ol><li id=\"c_7kdo\">Родился <b>23.08.1900</b> ветеран третьей &nbsp;<span style=\"color:red\"><i>инопланетной войны</i></span>,&nbsp;</li><li id=\"c_7kdo\">награжден <i>орденом </i>3 степени <b>Жилетки Вассермана</b>,&nbsp;</li><li id=\"c_7kdo\">в 40 лет стал <i>профессором </i>кафедры <b>лапшевешанья</b> университета УФО.</li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-04-02", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>&nbsp;</h1><p style="text-align: center;"><span style="color:red"><b><i>годовщина смерти Васи Пупкина.&nbsp;</i></b></span></p><ol><li id="c_7kdo">Родился <b>23.08.1900</b> ветеран третьей &nbsp;<span style="color:red"><i>инопланетной войны</i></span>,&nbsp;</li><li id="c_7kdo">награжден <i>орденом </i>3 степени <b>Жилетки Вассермана</b>,&nbsp;</li><li id="c_7kdo">в 40 лет стал <i>профессором </i>кафедры <b>лапшевешанья</b> университета УФО.</li></ol></div>' }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-6" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>05-02-15 Отложили!&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_fnfb\"><b><i>Набиев Б.И.</i></b> <span style=\"color:green\"><i>оглы </i></span>- ст. 30 ч.1, ст.228.1 ч.5 УК РФ;\n</li><li id=\"c_dxcd\"><b><i>Харитонов А.Г.</i></b> - ст.228.1 ч.3 п.а; ст.33 ч.3-ст.174.1 ч.3; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.4 п.а; ст.33 ч.3-ст.228.1 ч.3 п.п.а,г; ст. 30 ч.1, ст.33 ч.3-ст.228.1 ч.4 п.п.а,г; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.4 п.а УК РФ;\t</li><li id=\"c_l1hh\"><b><i>Шахбазов А.А</i></b>. <span style=\"color:blue\"><i>оглы </i></span>- ст. 30 ч.3, ст.228.1 ч.3 п.п.а,г; ст. 30 ч.1, ст.228.1 ч.5 УК РФ;&nbsp;</li><li id=\"c_5cce\"><b><i>Шахтарин И.С.</i></b> - ст.174.1 ч.3; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.4 п.а; ст.228.1 ч.3 п.п.а,г; ст. 30 ч.3, ст.228.1 ч.4 п.а УК РФ<br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-02-05", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1> Отложили!&nbsp;</h1><ul class="checkbox"><li id="c_fnfb"><b><i>Набиев Б.И.</i></b> <span style="color:green"><i>оглы </i></span>- ст. 30 ч.1, ст.228.1 ч.5 УК РФ;\n</li><li id="c_dxcd"><b><i>Харитонов А.Г.</i></b> - ст.228.1 ч.3 п.а; ст.33 ч.3-ст.174.1 ч.3; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.4 п.а; ст.33 ч.3-ст.228.1 ч.3 п.п.а,г; ст. 30 ч.1, ст.33 ч.3-ст.228.1 ч.4 п.п.а,г; ст. 30 ч.3, ст.33 ч.3-ст.228.1 ч.4 п.а УК РФ;	</li><li id="c_l1hh"><b><i>Шахбазов А.А</i></b>. <span style="color:blue"><i>оглы </i></span>- ст. 30 ч.3, ст.228.1 ч.3 п.п.а,г; ст. 30 ч.1, ст.228.1 ч.5 УК РФ;&nbsp;</li><li id="c_5cce"><b><i>Шахтарин И.С.</i></b> - ст.174.1 ч.3; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.3 п.а; ст. 30 ч.3, ст.228.1 ч.4 п.а; ст.228.1 ч.3 п.п.а,г; ст. 30 ч.3, ст.228.1 ч.4 п.а УК РФ<br></li></ul></div>' } // ожидает рабочее время пользователя
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-7" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\"><b><i>04 марта 2015 года</i></b> состоится&nbsp;</p><h1><span style=\"color:red\">Торжественное бракосочетание Олега и Татьяны.&nbsp;</span></h1><p style=\"text-align: left;\">Приглашаем вас&nbsp;</p><ul class=\"checkbox\"><li id=\"c_xsjy\">бла&nbsp;</li><li id=\"c_nzxb\">бла&nbsp;</li><li id=\"c_v1uo\">бла&nbsp;</li><li id=\"c_nw33\">бла&nbsp;</li><li id=\"c_4etv\">бла&nbsp;</li></ul><ol><li id=\"c_7sik\">бла&nbsp;</li><li id=\"c_7sik\">бла&nbsp;</li><li id=\"c_7sik\">бла&nbsp;</li></ol><ul><li id=\"c_3ijy\">бла&nbsp;</li><li id=\"c_3ijy\">бла&nbsp;</li><li id=\"c_3ijy\">бла бал.&nbsp;</li></ul><p style=\"text-align: justify;\">План мероприятия:&nbsp;</p><p>1. <b>в 9:00 Загс Приволжского района</b> г. Казани, зал № 9. Адрес : <i>ул. Зорге,д. 12-05.&nbsp;</i></p><p>2.<b>в 10:30 Парк культуры и отдыха</b> - фотосессия&nbsp;</p><p>3. <b>в 14:00 Кафе \'Свитер\'</b> <i>ул. Профсоюзная, 7,5.</i>&nbsp;</p><p style=\"text-align: right;\"><b>Подходить</b><i><b> </b>к 8:30</i></p><p></p><p></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-04", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><p style="text-align: center;"><b><i></i></b> состоится&nbsp;</p><h1><span style="color:red">Торжественное бракосочетание Олега и Татьяны.&nbsp;</span></h1><p style="text-align: left;">Приглашаем вас&nbsp;</p><ul class="checkbox"><li id="c_xsjy">бла&nbsp;</li><li id="c_nzxb">бла&nbsp;</li><li id="c_v1uo">бла&nbsp;</li><li id="c_nw33">бла&nbsp;</li><li id="c_4etv">бла&nbsp;</li></ul><ol><li id="c_7sik">бла&nbsp;</li><li id="c_7sik">бла&nbsp;</li><li id="c_7sik">бла&nbsp;</li></ol><ul><li id="c_3ijy">бла&nbsp;</li><li id="c_3ijy">бла&nbsp;</li><li id="c_3ijy">бла бал.&nbsp;</li></ul><p style="text-align: justify;">План мероприятия:&nbsp;</p><p>1. <b> Загс Приволжского района</b> г. Казани, зал № 9. Адрес : <i>ул. Зорге,д. 12-05.&nbsp;</i></p><p>2.<b>в 10:30 Парк культуры и отдыха</b> - фотосессия&nbsp;</p><p>3. <b>в 14:00 Кафе \'Свитер\'</b> <i>ул. Профсоюзная, 7,5.</i>&nbsp;</p><p style="text-align: right;"><b>Подходить</b><i><b> </b>к 8:30</i></p><p></p><p></p></div>'        },
			{ "event_type" : "N", "event_startDate" : "2015-03-04", "event_startTime" : "20:30", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\"><b><i></i></b> состоится&nbsp;</p><h1><span style=\"color:red\">Торжественное бракосочетание Олега и Татьяны.&nbsp;</span></h1><p style=\"text-align: left;\">Приглашаем вас&nbsp;</p><ul class=\"checkbox\"><li id=\"c_xsjy\">бла&nbsp;</li><li id=\"c_nzxb\">бла&nbsp;</li><li id=\"c_v1uo\">бла&nbsp;</li><li id=\"c_nw33\">бла&nbsp;</li><li id=\"c_4etv\">бла&nbsp;</li></ul><ol><li id=\"c_7sik\">бла&nbsp;</li><li id=\"c_7sik\">бла&nbsp;</li><li id=\"c_7sik\">бла&nbsp;</li></ol><ul><li id=\"c_3ijy\">бла&nbsp;</li><li id=\"c_3ijy\">бла&nbsp;</li><li id=\"c_3ijy\">бла бал.&nbsp;</li></ul><p style=\"text-align: justify;\">План мероприятия:&nbsp;</p><p>1. <b>План мероприятия: 1. <b>в 9:00 Загс Приволжского района</b> г. Казани, зал № 9. Адрес : <i>ул. Зорге,д. 12-05.&nbsp;</i></p><p>2.<b>в в 10:30 Парк культуры и отдыха</b> - фотосессия&nbsp;</p><p>3. <b>в 14:00 Кафе 'Свитер'</b> <i>ул. Профсоюзная, 7,5.</i>&nbsp;</p><p style=\"text-align: right;\"><b>Подходить</b><i><b> </b></i></p><p></p><p></p></div>"        },

			{ "event_type" : "N", "event_startDate" : "2015-03-03",                              "event_duration" : "30", "event_result" : "состоится Торжественное бракосочетание Олега и Татьяны. Приглашаем вас бла бла бла бла бла бла бла бла бла бла бла бал. План мероприятия: 1. в 9:00 Загс Приволжского района г. Казани, зал № 9. Адрес : ул. Зорге,д. 12-05. 2.в 10:30 Парк культуры и отдыха - фотосессия 3. в 14:00 Кафе 'Свитер' ул. Профсоюзная, 7,5. Подходить к 8:30" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-8" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>\'Август восьмого\'&nbsp;</h1><p>- российский кинофильм <b><i>Джаника Файзиева</i></b>&nbsp;</p><ul><li id=\"c_nzqj\">о конфликте в <span style=\"color:red\"><b>Южной Осетии</b></span>, произошедшем <i>в августе 2008 года</i>.&nbsp;</li></ul><ol><li id=\"c_9lyi\"><b>Премьера </b><i>21 февраля 2012 года</i>.&nbsp;</li><li id=\"c_9lyi\"><b>Телепремьера </b>на Первом канале <i>4го мая в 18:20</i>.</li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-08-01", "event_startTime" : "18:20", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>\'Август восьмого\'&nbsp;</h1><p>- российский кинофильм <b><i>Джаника Файзиева</i></b>&nbsp;</p><ul><li id="c_nzqj">о конфликте в <span style="color:red"><b>Южной Осетии</b></span>, произошедшем <i> 2008 года</i>.&nbsp;</li></ul><ol><li id="c_9lyi"><b>Премьера </b><i>21 февраля 2012 года</i>.&nbsp;</li><li id="c_9lyi"><b>Телепремьера </b>на Первом канале <i>4го мая</i>.</li></ol></div>'  }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-9" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>28.04 в 9:40&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_va44\"><span style=\"color:blue\"><b><i>ДЕЛО </i></b></span>№ 2-8811/2014 ~ М-8743/2014&nbsp;</li><li id=\"c_igq7\"><span style=\"color:red\"><b><i>КАТЕГОРИЯ:</i></b></span> Другие жилищные споры \n</li><li id=\"c_pmsv\"><span style=\"color:green\"><i><b>ИСТЕЦ(ЗАЯВИТЕЛЬ):</b></i></span> Данилов И.Д.&nbsp;</li></ul><ol><li id=\"c_2w99\"><b>Дата </b>поступления <i>23.10.2014</i> \t</li><li id=\"c_2w99\"><b>Начало </b>течения срока рассмотрения дела - <i>02.12.2014</i>&nbsp;</li></ol><p style=\"text-align: right;\"><i>напомнить за час</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-04-28", "event_startTime" : "09:40", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1> nbsp;</h1><ul class="checkbox"><li id="c_va44"><span style="color:blue"><b><i>ДЕЛО </i></b></span>№ 2-8811/2014 ~ М-8743/2014&nbsp;</li><li id="c_igq7"><span style="color:red"><b><i>КАТЕГОРИЯ:</i></b></span> Другие жилищные споры \n</li><li id="c_pmsv"><span style="color:green"><i><b>ИСТЕЦ(ЗАЯВИТЕЛЬ):</b></i></span> Данилов И.Д.&nbsp;</li></ul><ol><li id="c_2w99"><b>Дата </b>поступления <i>23.10.2014</i> 	</li><li id="c_2w99"><b>Начало </b>течения срока рассмотрения дела - <i>02.12.2014</i>&nbsp;</li></ol><p style="text-align: right;"><i></i></p></div>'                 , "event_alarms":"-60" },
			{ "event_type" : "N", "event_startDate" : "2015-04-28", "event_startTime" : "21:40", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_va44\"><span style=\"color:blue\"><b><i>ДЕЛО </i></b></span>№ 2-8811/2014 ~ М-8743/2014&nbsp;</li><li id=\"c_igq7\"><span style=\"color:red\"><b><i>КАТЕГОРИЯ:</i></b></span> Другие жилищные споры \n</li><li id=\"c_pmsv\"><span style=\"color:green\"><i><b>ИСТЕЦ(ЗАЯВИТЕЛЬ):</b></i></span> Данилов И.Д.&nbsp;</li></ul><ol><li id=\"c_2w99\"><b>Дата </b>поступления <i>23.10.2014</i> \t</li><li id=\"c_2w99\"><b>Начало </b>течения срока рассмотрения дела - <i>02.12.2014</i>&nbsp;</li></ol><p style=\"text-align: right;\"><i></i></p></div>"                 , "event_alarms":"-60" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-10" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p><span style=\"color:red\"><b><i>Праздничный новогодний концерт</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_t4uq\"><b>Ренат Салаватов</b> - заслуженный артист России, <span style=\"color:blue\"><i>народный артист Татарстана</i></span>. \n</li><li id=\"c_8k1i\">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id=\"c_px36\"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id=\"c_i0pk\"><b>27.03 </b>в 17:00&nbsp;</li><li id=\"c_i0pk\">на <b>2,5 часа</b>&nbsp;</li><li id=\"c_i0pk\">вы бла <i>бла&nbsp;</i></li></ol><p style=\"text-align: right;\"><b><i>бла бла</i></b></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-27", "event_startTime" : "17:00", "event_duration" : "150", "event_result" : '<div id="at_content" contenteditable="true"><p><span style="color:red"><b><i>Праздничный новогодний концерт</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class="checkbox"><li id="c_t4uq"><b>Ренат Салаватов</b> - заслуженный артист России, <span style="color:blue"><i>народный артист Татарстана</i></span>. \n</li><li id="c_8k1i">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id="c_px36"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id="c_i0pk"><b> </b> nbsp;</li><li id="c_i0pk">на <b></b>&nbsp;</li><li id="c_i0pk">вы бла <i>бла&nbsp;</i></li></ol><p style="text-align: right;"><b><i>бла бла</i></b></p></div>'					},

			{ "event_type" : "N", "event_startDate" : "2015-03-27", "event_duration" : "150", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p><span style=\"color:red\"><b><i>Праздничный новогодний концерт.</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_t4uq\"><b>Ренат Салаватов</b> - заслуженный артист России, <span style=\"color:blue\"><i>народный артист Татарстана</i></span>. \n</li><li id=\"c_8k1i\">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id=\"c_px36\"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id=\"c_i0pk\"><b> </b>в в 17:00&nbsp;</li><li id=\"c_i0pk\"> <b></b>&nbsp;</li><li id=\"c_i0pk\">вы бла <i>бла&nbsp;</i></li></ol><p style=\"text-align: right;\"><b><i>бла бла</i></b></p></div>"             },
			{ "event_type" : "N", "event_startDate" : "2015-03-27", "event_startTime" : "17:00", "event_duration" : "30",  "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p><span style=\"color:red\"><b><i>Праздничный новогодний концерт.</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_t4uq\"><b>Ренат Салаватов</b> - заслуженный артист России, <span style=\"color:blue\"><i>народный артист Татарстана</i></span>. \n</li><li id=\"c_8k1i\">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id=\"c_px36\"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id=\"c_i0pk\"><b> </b>&nbsp;</li><li id=\"c_i0pk\">на <b>2,5 часа</b>&nbsp;</li><li id=\"c_i0pk\">вы бла <i>бла&nbsp;</i></li></ol><p style=\"text-align: right;\"><b><i>бла бла</i></b></p></div>"       },
			{ "event_type" : "N", "event_startDate" : "2015-03-27", "event_duration" : "30",  "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p><span style=\"color:red\"><b><i>Праздничный новогодний концерт.</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_t4uq\"><b>Ренат Салаватов</b> - заслуженный артист России, <span style=\"color:blue\"><i>народный артист Татарстана</i></span>. \n</li><li id=\"c_8k1i\">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id=\"c_px36\"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id=\"c_i0pk\"><b> </b>в в 17:00&nbsp;</li><li id=\"c_i0pk\">на <b>2,5 часа</b>&nbsp;</li><li id=\"c_i0pk\">вы бла <i>бла&nbsp;</i></li></ol><p style=\"text-align: right;\"><b><i>бла бла</i></b></p></div>" },
			{ "event_type" : "N", "event_startTime" : "17:00", "event_duration" : "150", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p><span style=\"color:red\"><b><i>Праздничный новогодний концерт.</i></b></span>.&nbsp;</p><h1>Дирижер&nbsp;Ренат Салаватов.&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_t4uq\"><b>Ренат Салаватов</b> - заслуженный артист России, <span style=\"color:blue\"><i>народный артист Татарстана</i></span>. \n</li><li id=\"c_8k1i\">С 2003 г. – <b>главный дириже</b>р Татарского академического государственного <i>театра оперы и балета им.М.Джалиля</i>.&nbsp;</li><li id=\"c_px36\"><b>1700 - 3500</b> ГБКЗ им. С.Сайдашева&nbsp;</li></ul><ol><li id=\"c_i0pk\"><b>27.03 </b>&nbsp;</li><li id=\"c_i0pk\"> <b></b>&nbsp;</li><li id=\"c_i0pk\">вы бла <i>бла&nbsp;</i></li></ol><p style=\"text-align: right;\"><b><i>бла бла</i></b></p></div>"               }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-11" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\">В прошлое <span style=\"color:blue\"><i>воскресенье </i></span>состоялась <i><b>игра&nbsp;</b></i></p><h1>Сибирь:Лада&nbsp;</h1><ol><li id=\"c_os3f\">со счетом <span style=\"color:red\"><b>4:3</b></span>&nbsp;</li><li id=\"c_os3f\">и собрала <b>в 2 раза больше</b> зрителей <i>чем в прошлую встречу с <b>Сочи</b></i>.&nbsp;\n</li><li id=\"c_os3f\"><i>Следующая</i> игра <b>Сибири с Югрой</b> состоится&nbsp;</li></ol><p style=\"text-align: center;\"><b><i>28, апр. в 18:00</i></b><br></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-04-28", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\">В прошлое <span style=\"color:blue\"><i>воскресенье </i></span>состоялась <i><b>игра&nbsp;</b></i></p><h1>Сибирь:Лада&nbsp;</h1><ol><li id=\"c_os3f\">со счетом <span style=\"color:red\"><b>4:3</b></span>&nbsp;</li><li id=\"c_os3f\">и собрала <b>в 2 раза больше</b> зрителей <i>чем в прошлую встречу с <b>Сочи</b></i>.&nbsp;\n</li><li id=\"c_os3f\"><i>Следующая</i> игра <b>Сибири с Югрой</b> состоится&nbsp;</li></ol><p style=\"text-align: center;\"><b><i></i></b><br></p></div>"          },
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-12" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Подарки на Юбилей дядь Юры,&nbsp;</h1><p style=\"text-align: center;\">55 лет 15/03 \n</p><ul class=\"checkbox\"><li id=\"c_zg6n\">- <b>5000 </b>руб&nbsp;</li><li id=\"c_3s92\">- <span style=\"color:blue\"><i>норковая </i></span>шапка (<b>7 </b>тр)&nbsp;</li><li id=\"c_94e4\">- зубы (<i>золотые</i>) на брелке (<b>4</b> т.р.)&nbsp;</li><li id=\"c_uh9t\">-хвост <span style=\"color:red\"><i>скунса </i></span>на шапке (<b>3458</b> руб)\t</li></ul><p style=\"text-align: right;\">Напомнить<i> за 2 дня</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-15", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Подарки на Юбилей дядь Юры,&nbsp;</h1><p style="text-align: center;">55 лет \n</p><ul class="checkbox"><li id="c_zg6n">- <b>5000 </b>руб&nbsp;</li><li id="c_3s92">- <span style="color:blue"><i>норковая </i></span>шапка (<b>7 </b>тр)&nbsp;</li><li id="c_94e4">- зубы (<i>золотые</i>) на брелке (<b>4</b> т.р.)&nbsp;</li><li id="c_uh9t">-хвост <span style="color:red"><i>скунса </i></span>на шапке (<b>3458</b> руб)	</li></ul><p style="text-align: right;"><i></i></p></div>'                    , "event_alarms" : "-2880"},

			{ "event_type" : "N", "event_startDate" : "2015-03-15", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Подарки на Юбилей дядь Юры,&nbsp;</h1><p style=\"text-align: center;\">55 лет \n- 5000 руб - норковая шапка (7 тр) - зубы (золотые) на брелке (4 т.р.) -хвост скунса на шапке (3458 руб) Напомнить за 2 дня" } // ожидает рабочее время пользователя
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-13" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Рука Дьявола\n</h1><p><b><i>Where the Devil Hides </i></b>(16+)&nbsp;</p><ul><li id=\"c_bdyv\"><b>Триллер</b>, США, 2014, <i>86 мин</i>.&nbsp;</li><li id=\"c_bdyv\"><b>Режиссёр</b>: Кристиан Е. Кристиансен&nbsp;</li><li id=\"c_bdyv\"><b>В ролях</b>: <i>Руфус Сьюэлл</i>, <span style=\"color:red\">Алисия Дебнем Кери</span>, Томас МакДонелл, Аделаида Кэйн, <span style=\"color:red\">Леа Пайпс</span>, Рик Рейц, Дженнифер Карпентер, Колм Мини, Джим Маккини, <i>Николь Эллиотт&nbsp;</i></li></ul><p style=\"text-align: right;\"><b><i>Дата премьеры:</i></b> 18,Фев<br></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2016-02-18", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Рука Дьявола\n</h1><p><b><i>Where the Devil Hides </i></b>(16+)&nbsp;</p><ul><li id=\"c_bdyv\"><b>Триллер</b>, США, 2014, <i>86 мин</i>.&nbsp;</li><li id=\"c_bdyv\"><b>Режиссёр</b>: Кристиан Е. Кристиансен&nbsp;</li><li id=\"c_bdyv\"><b>В ролях</b>: <i>Руфус Сьюэлл</i>, <span style=\"color:red\">Алисия Дебнем Кери</span>, Томас МакДонелл, Аделаида Кэйн, <span style=\"color:red\">Леа Пайпс</span>, Рик Рейц, Дженнифер Карпентер, Колм Мини, Джим Маккини, <i>Николь Эллиотт&nbsp;</i></li></ul><p style=\"text-align: right;\"><b><i>Дата премьеры:</i></b><br></p></div>" } // ожидает рабочее время пользователя
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-14" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\"><i><b>Евросоюз выделил Украине</b></i>&nbsp;</p><ol><li id=\"c_8qxp\">500 миллионов евро в рамках <i>второй программы</i> <b><i>макрофинансовой помощи</i></b> (<b>MFA2</b>) <i>3 декабря</i>.&nbsp;</li><li id=\"c_8qxp\"><b><i>В течение 2014 года</i></b> Украина получала <b>100 миллионов евро</b> <i>20 мая</i>,&nbsp;</li><li id=\"c_8qxp\"><b>500 миллионов</b> — <i>17 июня </i>,&nbsp;</li><li id=\"c_8qxp\"><b>260 миллионов</b> — <i>12 ноября</i>.&nbsp;</li></ol><h1>Общий объем поддержки составляет 1,61 миллиарда евро.</h1><ul><li id=\"c_ciq3\">Россия нарушила <i>принципы Всемирной торговой организации</i> (<b>ВТО</b>), введя <span style=\"color:blue\">ограничения</span> в ответ на санкции США, Евросоюза и ряд других стран.&nbsp;</li><li id=\"c_icx3\">Такие утверждения содержатся в <span style=\"color:darkred\">докладе</span> офиса торгового представителя <b>Соединенных Штатов</b>, опубликованном <i>29,05</i>.</li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-03", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><p style="text-align: center;"><i><b>Евросоюз выделил Украине</b></i>&nbsp;</p><ol><li id="c_8qxp">500 миллионов евро в рамках <i>второй программы</i> <b><i>макрофинансовой помощи</i></b> (<b>MFA2</b>) <i></i>.&nbsp;</li><li id="c_8qxp"><b><i>В течение 2014 года</i></b> Украина получала <b>100 миллионов евро</b> <i>20 мая</i>,&nbsp;</li><li id="c_8qxp"><b>500 миллионов</b> — <i>17 июня </i>,&nbsp;</li><li id="c_8qxp"><b>260 миллионов</b> — <i>12 ноября</i>.&nbsp;</li></ol><h1>Общий объем поддержки составляет 1,61 миллиарда евро.</h1><ul><li id="c_ciq3">Россия нарушила <i>принципы Всемирной торговой организации</i> (<b>ВТО</b>), введя <span style="color:blue">ограничения</span> в ответ на санкции США, Евросоюза и ряд других стран.&nbsp;</li><li id="c_icx3">Такие утверждения содержатся в <span style="color:darkred">докладе</span> офиса торгового представителя <b>Соединенных Штатов</b>, опубликованном <i>29,05</i>.</li></ul></div>' } // ожидает рабочее время пользователя
		],		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-15" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Я сделал и таблицу динамики явки.&nbsp;</h1><p style=\"text-align: center;\">То есть <b><i>какая доля людей</i></b>, пришедших на участки, сделала это&nbsp;</p><ol><li id=\"c_pny2\"><i>с 8 до 12</i> часов,&nbsp;</li><li id=\"c_pny2\"><i>с 12 до 15</i> часов и т.д.&nbsp;</li></ol><p style=\"text-align: justify;\">Вот тут начинается <b>самое интересное</b>.&nbsp;</p><ul><li id=\"c_68wq\">Чаще всего выглядит <b><i>ужасно</i></b>, неправдоподобно и это явное <span style=\"color:red\">свидетельство</span> <b>манипуляций</b>.</li><li id=\"c_68wq\">&nbsp;<b>Самый большой</b> наплыв людей идет <i>с 10 до 14 - 15 </i>часов, а потом идет <b>спад</b>.</li><li id=\"c_68wq\">&nbsp;Но не могут <b><i>9%</i></b> от всех пришедших за день проголосовать <i>в 15 до 18 </i>часов и <b><i>20%</i> </b><i>с 18 до 20</i> часов, как было в <b>Евпатории</b></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "12:00", "event_duration" : "180",  "event_result" : '<div id="at_content" contenteditable="true"><h1>Я сделал и таблицу динамики явки.&nbsp;</h1><p style="text-align: center;">То есть <b><i>какая доля людей</i></b>, пришедших на участки, сделала это&nbsp;</p><ol><li id="c_pny2"><i>с 8 до 12</i> часов,&nbsp;</li><li id="c_pny2"><i></i> часов и т.д.&nbsp;</li></ol><p style="text-align: justify;">Вот тут начинается <b>самое интересное</b>.&nbsp;</p><ul><li id="c_68wq">Чаще всего выглядит <b><i>ужасно</i></b>, неправдоподобно и это явное <span style="color:red">свидетельство</span> <b>манипуляций</b>.</li><li id="c_68wq">&nbsp;<b>Самый большой</b> наплыв людей идет <i>с 10 до 14 - 15 </i>часов, а потом идет <b>спад</b>.</li><li id="c_68wq">&nbsp;Но не могут <b><i>9%</i></b> от всех пришедших за день проголосовать <i>в 15 до 18 </i>часов и <b><i>20%</i> </b><i>с 18 до 20</i> часов, как было в <b>Евпатории</b></li></ul></div>' },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "20:00", "event_duration" : "240", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Я сделал и таблицу динамики явки.&nbsp;</h1><p style=\"text-align: center;\">То есть <b><i>какая доля людей</i></b>, пришедших на участки, сделала это&nbsp;</p><ol><li id=\"c_pny2\"><i></i>&nbsp;</li><li id=\"c_pny2\"><i> с 12 до 15 часов</i> и т.д.&nbsp;</li></ol><p style=\"text-align: justify;\">Вот тут начинается <b>самое интересное</b>.&nbsp;</p><ul><li id=\"c_68wq\">Чаще всего выглядит <b><i>ужасно</i></b>, неправдоподобно и это явное <span style=\"color:red\">свидетельство</span> <b>манипуляций</b>.</li><li id=\"c_68wq\">&nbsp;<b>Самый большой</b> наплыв людей идет <i>с 10 до 14 - 15 </i>часов, а потом идет <b>спад</b>.</li><li id=\"c_68wq\">&nbsp;Но не могут <b><i>9%</i></b> от всех пришедших за день проголосовать <i>в 15 до 18 </i>часов и <b><i>20%</i> </b><i>с 18 до 20</i> часов, как было в <b>Евпатории</b></li></ul></div>" },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "08:00", "event_duration" : "240", "event_result" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Я сделал и таблицу динамики явки.&nbsp;</h1><p style=\"text-align: center;\">То есть <b><i>какая доля людей</i></b>, пришедших на участки, сделала это&nbsp;</p><ol><li id=\"c_pny2\"><i></i>&nbsp;</li><li id=\"c_pny2\"><i> с 12 до 15 часов</i> и т.д.&nbsp;</li></ol><p style=\"text-align: justify;\">Вот тут начинается <b>самое интересное</b>.&nbsp;</p><ul><li id=\"c_68wq\">Чаще всего выглядит <b><i>ужасно</i></b>, неправдоподобно и это явное <span style=\"color:red\">свидетельство</span> <b>манипуляций</b>.</li><li id=\"c_68wq\">&nbsp;<b>Самый большой</b> наплыв людей идет <i>с 10 до 14 - 15 </i>часов, а потом идет <b>спад</b>.</li><li id=\"c_68wq\">&nbsp;Но не могут <b><i>9%</i></b> от всех пришедших за день проголосовать <i>в 15 до 18 </i>часов и <b><i>20%</i> </b><i>с 18 до 20</i> часов, как было в <b>Евпатории</b></li></ul></div>" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-16" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_i8jq\"><b><i>В 15 часов</i></b>&nbsp;</li></ul><p style=\"text-align: justify;\"><b>сходить </b>отправить <i>письма</i>:&nbsp;</p><ul class=\"checkbox\"><li id=\"c_38oh\"><span style=\"color:red\"><b>Елена</b></span> 426756 Колыма, <i>ул. Ленина 15-52</i>,&nbsp;</li><li id=\"c_8cm6\"><span style=\"color:blue\"><b>Евкакий </b></span>201295 Ростов, <i>Якуба Коласа 17-35</i>,&nbsp;</li><li id=\"c_2944\"><span style=\"color:green\"><b>Пафнутий </b></span>Северодвинск 422561 <i>Октябрят 3-25</i><br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "15:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ul><li id="c_i8jq"><b><i></i></b>&nbsp;</li></ul><p style="text-align: justify;"><b>сходить </b>отправить <i>письма</i>:&nbsp;</p><ul class="checkbox"><li id="c_38oh"><span style="color:red"><b>Елена</b></span> 426756 Колыма, <i>ул. Ленина 15-52</i>,&nbsp;</li><li id="c_8cm6"><span style="color:blue"><b>Евкакий </b></span>201295 Ростов, <i>Якуба Коласа 17-35</i>,&nbsp;</li><li id="c_2944"><span style="color:green"><b>Пафнутий </b></span>Северодвинск 422561 <i>Октябрят 3-25</i><br></li></ul></div>' }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-17" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>В субботу <span style=\"color:red\">в 6 часов вечера</span>&nbsp;</h1><p><b><i>напомнить</i></b> сходить за <b>продуктами</b>:&nbsp;</p><ul class=\"checkbox\"><li id=\"c_r9ls\"><i>хлеб</i> 20.00,&nbsp;</li><li id=\"c_6su6\"><i>молоко </i>27.00,&nbsp;</li><li id=\"c_56p1\"><i>сырки </i>по 5.20 5 шт.,&nbsp;</li><li id=\"c_5a4n\"><i>сода </i>1 уп.,&nbsp;</li><li id=\"c_05vp\"><i>кефир </i>2,5% 2 пакета ,&nbsp;</li><li id=\"c_qzqv\">2-3 уп. <i>макарон</i>,&nbsp;</li><li id=\"c_xag5\"><i>сыр </i>200г 56-50,&nbsp;</li><li id=\"c_24qr\"><i>сосиски </i>96.20</li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1> <span style="color:red"></span>&nbsp;</h1><p><b><i></i></b> сходить за <b>продуктами</b>:&nbsp;</p><ul class="checkbox"><li id="c_r9ls"><i>хлеб</i> 20.00,&nbsp;</li><li id="c_6su6"><i>молоко </i>27.00,&nbsp;</li><li id="c_56p1"><i>сырки </i>по 5.20 5 шт.,&nbsp;</li><li id="c_5a4n"><i>сода </i>1 уп.,&nbsp;</li><li id="c_05vp"><i>кефир </i>2,5% 2 пакета ,&nbsp;</li><li id="c_qzqv">2-3 уп. <i>макарон</i>,&nbsp;</li><li id="c_xag5"><i>сыр </i>200г 56-50,&nbsp;</li><li id="c_24qr"><i>сосиски </i>96.20</li></ul></div>'                  , "event_alarms" : "0"},

			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "06:00", "event_duration" : "30", "event_result" : "вечера сходить за продуктами: хлеб 20.00, молоко 27.00, сырки по 5.20 5 шт., сода 1 уп., кефир 2,5% 2 пакета , 2-3 уп. макарон, сыр 200г 56-50, сосиски 96.20"           , "event_alarms" : "0"},
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "18:00", "event_duration" : "30", "event_result" : "напомнить сходить за продуктами: хлеб 20.00, молоко 27.00, сырки по 5.20 5 шт., сода 1 уп., кефир 2,5% 2 пакета , 2-3 уп. макарон, сыр 200г 56-50, сосиски 96.20"        },
			{ "event_type" : "N", "event_startDate" : "2015-03-14",                              "event_duration" : "30", "event_result" : "в 6 часов вечера сходить за продуктами: хлеб 20.00, молоко 27.00, сырки по 5.20 5 шт., сода 1 уп., кефир 2,5% 2 пакета , 2-3 уп. макарон, сыр 200г 56-50, сосиски 96.20" },
			{ "event_type" : "N",                                            "event_startTime" : "18:00", "event_duration" : "30", "event_result" : "В субботу сходить за продуктами: хлеб 20.00, молоко 27.00, сырки по 5.20 5 шт., сода 1 уп., кефир 2,5% 2 пакета , 2-3 уп. макарон, сыр 200г 56-50, сосиски 96.20"        }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-18" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Поздравления для Антона,&nbsp;</h1><p style=\"text-align: center;\"><b>завтра</b> в 21.00<b><i> Напомнить!&nbsp;</i></b></p><ul><li id=\"c_pcv4\">Сегодня ваш <span style=\"color:red\">знакомый юбиляр</span> празднует свой<b> 30-й день рождения</b>?&nbsp;</li><li id=\"c_pcv4\">Если вы хотите оригинально, а может быть, с юмором, поздравить <b>с 30-летним юбилеем</b> своих друзей и близких, причем, <span style=\"color:blue\">сделать это в стихах по смс</span>, то <i>данный </i>раздел — для вас!\n</li></ul><p style=\"text-align: justify;\"><b>Здесь </b>вы найдете <i>универсальные, адресные, иногда шуточные и прикольные </i>поздравления <b>с юбилеем 30 лет</b>, написанные <i>в стихах для родных и близких.</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "21:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Поздравления для Антона,&nbsp;</h1><p style="text-align: center;"><b></b><b><i>!&nbsp;</i></b></p><ul><li id="c_pcv4">Сегодня ваш <span style="color:red">знакомый юбиляр</span> празднует свой<b> 30-й день рождения</b>?&nbsp;</li><li id="c_pcv4">Если вы хотите оригинально, а может быть, с юмором, поздравить <b>с 30-летним юбилеем</b> своих друзей и близких, причем, <span style="color:blue">сделать это в стихах по смс</span>, то <i>данный </i>раздел — для вас!\n</li></ul><p style="text-align: justify;"><b>Здесь </b>вы найдете <i>универсальные, адресные, иногда шуточные и прикольные </i>поздравления <b>с юбилеем 30 лет</b>, написанные <i>в стихах для родных и близких.</i></p></div>',                    "event_alarms" : "0"  },

			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "21:00", "event_duration" : "30", "event_result" : "Поздравления для Антона, Напомнить! Сегодня ваш знакомый юбиляр празднует свой 30-й день рождения? Если вы хотите оригинально, а может быть, с юмором, поздравить с 30-летним юбилеем своих друзей и близких, причем, сделать это в стихах по смс, то данный раздел — для вас!"                              },
			{ "event_type" : "N", "event_startDate" : "2015-03-14",                              "event_duration" : "30", "event_result" : "Поздравления для Антона, в 21.00 Сегодня ваш знакомый юбиляр празднует свой 30-й день рождения? Если вы хотите оригинально, а может быть, с юмором, поздравить с 30-летним юбилеем своих друзей и близких, причем, сделать это в стихах по смс, то данный раздел — для вас!",            "event_alarms" : "0"  },
			{ "event_type" : "N", "event_startDate" : "2015-03-14",                              "event_duration" : "30", "event_result" : "Поздравления для Антона, в 21.00 Напомнить! Сегодня ваш знакомый юбиляр празднует свой 30-й день рождения? Если вы хотите оригинально, а может быть, с юмором, поздравить с 30-летним юбилеем своих друзей и близких, причем, сделать это в стихах по смс, то данный раздел — для вас!"                      }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-19" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>«Рубин» (тат. Рубин Казан футбол төркеме)&nbsp;</h1><p>— российский <b><i>футбольный клуб</i></b> из города <b>Казани</b>.&nbsp;</p><ul><li id=\"c_5znv\">Один из лидеров <span style=\"color:red\">российского футбола</span> второй половины <i>2000-х годов</i>.&nbsp;</li><li id=\"c_5znv\">Основан <i>в 1958 году</i>.&nbsp;</li><li id=\"c_5znv\">Двукратный чемпион России <i>2008 и 2009 годов</i>.&nbsp;</li></ul><p><b><i>Обладатель&nbsp;</i></b></p><ol><li id=\"c_bepz\">Кубка<i> России </i>2012,&nbsp;</li><li id=\"c_bepz\">Кубка <i>Содружества </i>2010,&nbsp;</li><li id=\"c_bepz\">Суперкубка <i>России </i>2010&nbsp;</li><li id=\"c_bepz\">и Суперкубка <i>России </i>2012.&nbsp;</li></ol><p style=\"text-align: justify;\">В 2009 году был признан <b><i>лучшей командой года</i></b> по версии <b>Российского футбольного союза</b>[3].<br></p></div>",
		"expectations" : [
		],
		"environment" : { "time" : "10:00", "date" : "2015-02-28" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-20" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>12 августа 14 года&nbsp;</h1><p>группа<b style=\"font-style: italic;\"> из 12-15 человек&nbsp;</b></p><p style=\"text-align: justify;\">устроила <span style=\"color:red\"><b>беспорядки </b></span>в районе рынка по адресу&nbsp;</p><ul><li id=\"c_76xj\">ул. Полыгалова,д. 15/2&nbsp;</li></ul><p style=\"text-align: right;\">- <span style=\"color:blue\">возбуждено</span> <i>уголовное дело</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate": "2014-08-12",   "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>&nbsp;</h1><p>группа<b style="font-style: italic;"> из 12-15 человек&nbsp;</b></p><p style="text-align: justify;">устроила <span style="color:red"><b>беспорядки </b></span>в районе рынка по адресу&nbsp;</p><ul><li id="c_76xj">ул. Полыгалова,д. 15/2&nbsp;</li></ul><p style="text-align: right;">- <span style="color:blue">возбуждено</span> <i>уголовное дело</i></p></div>'}
		],
		"environment" : { "time" : "18:00", "date" : "2015-03-12" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-21" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ol><li id=\"c_s63f\">в <b>пятницу</b>&nbsp;</li><li id=\"c_s63f\">в <b>7</b>&nbsp;</li></ol><h1>встреча с гопниками,&nbsp;</h1><p style=\"text-align: justify;\">там нам <b><i>объяснят</i></b>,&nbsp;</p><ul class=\"checkbox\"><li id=\"c_1jgk\">как нужно вести себя с <span style=\"color:red\"><b>высокопочтенными</b></span> на <i>районе людьми</i>,&nbsp;</li><li id=\"c_n20h\">на повестке - <b>результаты </b>нашей <span style=\"color:blue\">мимолетной</span> встречи <i>на прошлой неделе</i><br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-05-15" ,   "event_startTime" : "07:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ol><li id="c_s63f">в <b></b>&nbsp;</li><li id="c_s63f"> <b></b>&nbsp;</li></ol><h1>встреча с гопниками,&nbsp;</h1><p style="text-align: justify;">там нам <b><i>объяснят</i></b>,&nbsp;</p><ul class="checkbox"><li id="c_1jgk">как нужно вести себя с <span style="color:red"><b>высокопочтенными</b></span> на <i>районе людьми</i>,&nbsp;</li><li id="c_n20h">на повестке - <b>результаты </b>нашей <span style="color:blue">мимолетной</span> встречи <i>на прошлой неделе</i><br></li></ul></div>'},
			{ "event_type" : "N", "event_startDate" : "2015-05-15" ,   "event_startTime" : "19:00", "event_duration" : "30", "event_result" : "встреча с гопниками, там нам объяснят, как нужно вести себя с высокопочтенными на районе людьми, на повестке - результаты нашей мимолетной встречи на прошлой неделе"}
		],
		"environment" : { "time" : "06:00", "date" : "2015-05-10" , "workTime" : { "Mo" : "09:00-18:00", "Tu" : "09:00-18:00", "We" : "09:00-18:00", "Th" : "09:00-18:00", "Fr" : "09:00-18:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-22" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_6g5q\">суббота\n</li><li id=\"c_6g5q\">2 января,&nbsp;</li></ul><h1><span style=\"color:greenyellow\">Casting/Кастинг</span>&nbsp;</h1><p style=\"text-align: justify;\">Спектакль <span style=\"color:red\"><b><i>Casting/Кастинг</i></b></span> Театр им. <b>Моссовета</b>,&nbsp;</p><ol><li id=\"c_rg95\"><b>19:00</b>&nbsp;</li><li id=\"c_rg95\"><i>Русская версия</i> бродвейского мюзикла</li><li id=\"c_rg95\">Фотографии&nbsp;<b>6&nbsp;</b></li></ol><p style=\"text-align: right;\"><i><b>Напомнить за сутки</b></i></p></div>!",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2016-01-02", "event_startTime" : "19:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ul><li id="c_6g5q">,&nbsp;</li></ul><h1><span style="color:greenyellow">Casting/Кастинг</span>&nbsp;</h1><p style="text-align: justify;">Спектакль <span style="color:red"><b><i>Casting/Кастинг</i></b></span> Театр им. <b>Моссовета</b>,&nbsp;</p><ol><li id="c_rg95"><b></b>&nbsp;</li><li id="c_rg95"><i>Русская версия</i> бродвейского мюзикла</li><li id="c_rg95">Фотографии&nbsp;<b>6&nbsp;</b></li></ol><p style="text-align: right;"><i><b></b></i></p></div>!', "event_alarms" : "-1440"},

			{ "event_type" : "N", "event_startDate" : "2016-01-02", "event_startTime" : "19:00", "event_duration" : "30", "event_result" : "пятница\nCasting/Кастинг Спектакль Casting/Кастинг Театр им. Моссовета, Русская версия бродвейского мюзикла Фотографии 6 Напомнить за сутки!"           },
			{ "event_type" : "N", "event_startDate" : "2016-01-02",                              "event_duration" : "30", "event_result" : "пятница\nCasting/Кастинг Спектакль Casting/Кастинг Театр им. Моссовета, 19:00 Русская версия бродвейского мюзикла Фотографии 6!"                       },
			{ "event_type" : "N", "event_startDate" : "2016-01-02",                              "event_duration" : "30", "event_result" : "пятница\nCasting/Кастинг Спектакль Casting/Кастинг Театр им. Моссовета, 19:00 Русская версия бродвейского мюзикла Фотографии 6 Напомнить за сутки!"     },
			{ "event_type" : "N",                                                 "event_startTime" : "19:00", "event_duration" : "30", "event_result" : "2 января, пятница\nCasting/Кастинг Спектакль Casting/Кастинг Театр им. Моссовета, Русская версия бродвейского мюзикла Фотографии 6!"                   },
			{ "event_type" : "N",                                                 "event_startTime" : "19:00", "event_duration" : "30", "event_result" : "2 января, пятница\nCasting/Кастинг Спектакль Casting/Кастинг Театр им. Моссовета, Русская версия бродвейского мюзикла Фотографии 6 Напомнить за сутки!" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-23" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1><span style=\"color:red\">Из-за всего этого покупка валюты сократилась, но и её продажи пока относительное невелики</span>&nbsp;</h1><p style=\"text-align: justify;\">(<b><i>за 4 часа торгов</i></b> объем сделок в паре <i>доллар/рубль</i> расчетами завтра - менее <b>$1,8 миллиарда</b>):&nbsp;</p><ul><li id=\"c_f7zp\"><i>участники рынка</i> стараются изыскивать рублевые ресурсы через <span style=\"color:blue\">другие инструменты</span>, нежели используя продажу валюты.</li></ul><ol><li id=\"c_ku6w\"><i>К 14.25</i> МСК доллар США расчетами <b>\'завтра\'</b> оценивался в <b>55,93</b> рубля, что на 4,5 процента ниже предыдущего закрытия.&nbsp;</li><li id=\"c_ku6w\">Ранее доллар упал на <b>55,75</b> - минимум <i>с 11 декабря</i>.&nbsp;</li><li id=\"c_ku6w\"><i>Пара евро/рубль</i> расчетами <b>\'завтра\'</b> к этому времени торговалась вблизи отметки <b>68,58</b>, что на <b>5,4 процента</b> ниже предыдущего закрытия.</li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "14:25", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1><span style="color:red">Из-за всего этого покупка валюты сократилась, но и её продажи пока относительное невелики</span>&nbsp;</h1><p style="text-align: justify;">(<b><i>за 4 часа торгов</i></b> объем сделок в паре <i>доллар/рубль</i> расчетами менее <b>$1,8 миллиарда</b>):&nbsp;</p><ul><li id="c_f7zp"><i>участники рынка</i> стараются изыскивать рублевые ресурсы через <span style="color:blue">другие инструменты</span>, нежели используя продажу валюты.</li></ul><ol><li id="c_ku6w"><i></i> МСК доллар США расчетами <b>\'завтра\'</b> оценивался в <b>55,93</b> рубля, что на 4,5 процента ниже предыдущего закрытия.&nbsp;</li><li id="c_ku6w">Ранее доллар упал на <b>55,75</b> - минимум <i>с 11 декабря</i>.&nbsp;</li><li id="c_ku6w"><i>Пара евро/рубль</i> расчетами <b>\'завтра\'</b> к этому времени торговалась вблизи отметки <b>68,58</b>, что на <b>5,4 процента</b> ниже предыдущего закрытия.</li></ol></div>'         }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-24" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>В будние дни уже<b>&nbsp;</b></h1><ul><li id=\"c_n245\"><b>в 5 утра</b> по московскому времени <span style=\"color:red\"><i>начинается рост</i></span> посещаемости за счет дальневосточной и сибирской аудитории.&nbsp;</li><li id=\"c_n245\"><b style=\"line-height: 21.25px;\">8 утра</b>, когда просыпаются москвичи, <i>рост резко ускоряется</i>, и уже&nbsp;</li><li id=\"c_n245\"><b style=\"line-height: 21.25px;\">к 11 часам</b> активность аудитории <i>в 4 раза превышает</i> минимальный ночной уровень.&nbsp;</li></ul><p style=\"text-align: justify;\">При этом <b><i>пик посещаемости</i></b> в будние дни растянут во времени: только в районе <b>6 вечера</b>, с окончанием рабочего дня для посетителей из московского часового пояса, посещаемость <i>начинает сокращаться</i>.&nbsp;</p><p style=\"text-align: left;\">Вплоть <i>до </i><b>9 вечера</b> каждый час аудитория <i>сокращается </i>примерно на 30-40 тысяч человек, а <i>после </i><b>9 вечера</b> спад замедляется до 10-20 тысяч человек в час.<br></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "05:00",  "event_duration" : "960", "event_result" : "В будние дни уже по московскому времени начинается рост посещаемости за счет дальневосточной и сибирской аудитории. В 8 утра, когда просыпаются москвичи, рост резко ускоряется, и уже к 11 часам активность аудитории в 4 раза превышает минимальный ночной уровень. При этом пик посещаемости в будние дни растянут во времени: только в районе 6 вечера, с окончанием рабочего дня для посетителей из московского часового пояса, посещаемость начинает сокращаться. Вплоть каждый час аудитория сокращается примерно на 30-40 тысяч человек, а после 9 вечера спад замедляется до 10-20 тысяч человек в час."      }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-25" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Загорелась одна из квартир. \n</h1><p style=\"text-align: center;\">Как сообщили в пресс-службе <span style=\"color:blue\"><b>ГУ МЧС России</b></span> по <i>Новосибирской области</i>,</p><ol><li id=\"c_s8nf\"><b>22 декабря</b>,&nbsp;</li><li id=\"c_s8nf\"><i style=\"line-height: 21.25px;\"><b>в 04:07</b></i>&nbsp;</li><li id=\"c_s8nf\">случился <span style=\"color:red\">крупный пожар</span> в жилом доме, расположенном <i style=\"line-height: 21.25px;\">в переулке Петропавловском, 4.</i>&nbsp;</li></ol><ul><li id=\"c_iyty\">Сотрудники МЧС тут же выехали на место, предотвратили распространение огня и эвакуировали из подъезда <b>8 человек</b>.&nbsp;</li><li id=\"c_p0rf\">В <b><i>04:26</i></b> пожар был <i>потушен</i>.</li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "16:07", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Загорелась одна из квартир. \n</h1><p style="text-align: center;">Как сообщили в пресс-службе <span style="color:blue"><b>ГУ МЧС России</b></span> по <i>Новосибирской области</i>,</p><ol><li id="c_s8nf"><b></b>,&nbsp;</li><li id="c_s8nf"><i style="line-height: 21.25px;"><b></b></i>&nbsp;</li><li id="c_s8nf">случился <span style="color:red">крупный пожар</span> в жилом доме, расположенном <i style="line-height: 21.25px;">в переулке Петропавловском, 4.</i>&nbsp;</li></ol><ul><li id="c_iyty">Сотрудники МЧС тут же выехали на место, предотвратили распространение огня и эвакуировали из подъезда <b>8 человек</b>.&nbsp;</li><li id="c_p0rf">В <b><i>04:26</i></b> пожар был <i>потушен</i>.</li></ul></div>' },
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "04:07", "event_duration" : "30", "event_result" : "Загорелась одна из квартир. \nКак сообщили в пресс-службе ГУ МЧС России по Новосибирской области, случился крупный пожар в жилом доме, расположенном в переулке Петропавловском, 4. Сотрудники МЧС тут же выехали на место, предотвратили распространение огня и эвакуировали из подъезда 8 человек. В 04:26 пожар был потушен." },
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "16:26", "event_duration" : "30", "event_result" : "Загорелась одна из квартир. \nКак сообщили в пресс-службе ГУ МЧС России по Новосибирской области, случился крупный пожар в жилом доме, расположенном в переулке Петропавловском, 4. Сотрудники МЧС тут же выехали на место, предотвратили распространение огня и эвакуировали из подъезда 8 человек. пожар был потушен." },
			{ "event_type" : "N", "event_startDate" : "2015-12-22", "event_startTime" : "04:26", "event_duration" : "30", "event_result" : "Загорелась одна из квартир. \nКак сообщили в пресс-службе ГУ МЧС России по Новосибирской области, случился крупный пожар в жилом доме, расположенном в переулке Петропавловском, 4. Сотрудники МЧС тут же выехали на место, предотвратили распространение огня и эвакуировали из подъезда 8 человек. пожар был потушен." }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-26" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_eh5d\">В очереди пришлось стоять почти <b><i>4 часа</i></b>, но ради <span style=\"color:red\">любимой тещи</span> я готов сделать <b>что угодно</b>! \n</li><li id=\"c_u243\">Самое интересное началось <i><b>в 20.45</b></i>, когда сказали, что через <b><i>15 минут </i></b>магазин <b>закрывается</b>.&nbsp;</li></ul><h1>В кассу стояло еще человек 50-70.&nbsp;</h1><ol><li id=\"c_fmxo\">Я думал, случится <span style=\"color:red\"><b>революция</b></span>, но магазин не закрыли.&nbsp;</li><li id=\"c_fmxo\">Сам я расплатился за <i style=\"line-height: 21.25px;\">телевизор </i><b style=\"line-height: 21.25px;\">в 21.15</b>.</li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "20:45", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ul><li id="c_eh5d">В очереди пришлось стоять почти <b><i>4 часа</i></b>, но ради <span style="color:red">любимой тещи</span> я готов сделать <b>что угодно</b>! \n</li><li id="c_u243">Самое интересное началось <i><b></b></i>, когда сказали, что через <b><i>15 минут </i></b>магазин <b>закрывается</b>.&nbsp;</li></ul><h1>В кассу стояло еще человек 50-70.&nbsp;</h1><ol><li id="c_fmxo">Я думал, случится <span style="color:red"><b>революция</b></span>, но магазин не закрыли.&nbsp;</li><li id="c_fmxo">Сам я расплатился за <i style="line-height: 21.25px;">телевизор </i><b style="line-height: 21.25px;">в 21.15</b>.</li></ol></div>' },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "09:15", "event_duration" : "30", "event_result" : "В очереди пришлось стоять почти 4 часа, но ради любимой тещи я готов сделать что угодно! \nСамое интересное началось в 20.45, когда сказали, что магазин закрывается. В кассу стояло еще человек 50-70. Я думал, случится революция, но магазин не закрыли. Сам я расплатился за телевизор в 21.15." },
			{ "event_type" : "N", "event_startDate" : "2015-03-13", "event_startTime" : "21:15", "event_duration" : "30", "event_result" : "В очереди пришлось стоять почти 4 часа, но ради любимой тещи я готов сделать что угодно! \nСамое интересное началось в 20.45, когда сказали, что через 15 минут магазин закрывается. В кассу стояло еще человек 50-70. Я думал, случится революция, но магазин не закрыли. Сам я расплатился за телевизор." }

		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-27" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: justify;\">Из-за приближающегося <b><i>Нового года</i></b> выросло количество машин на дорогах в выходные.&nbsp;</p><p style=\"text-align: left;\">Пробки в субботу составили <b>6 баллов</b>, в воскресенье –<b> 3 балла</b>.&nbsp;</p><h1>Это выше, чем обычно.&nbsp;</h1><p style=\"text-align: center;\"><b><i>Топ-5 пробок</i></b> в Новосибирске <span style=\"color:darkblue\"><i>с 15 по 21 декабря 2014 года</i></span>:&nbsp;</p><ol><li id=\"c_oic8\">Пробка в 12,8 км - <i>17 декабря</i>,&nbsp;</li><li id=\"c_oic8\"><b>около 9:00</b> - Бердское шоссе,&nbsp;</li><li id=\"c_oic8\">Большевистская улица - от Старого шоссе до <span style=\"color:red\">Красного проспекта</span> - <b>3 часа 10 минут</b>.</li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-03-14", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><p style="text-align: justify;">Из-за приближающегося <b><i>Нового года</i></b> выросло количество машин на дорогах в выходные.&nbsp;</p><p style="text-align: left;">Пробки составили <b>6 баллов</b>, в воскресенье –<b> 3 балла</b>.&nbsp;</p><h1>Это выше, чем обычно.&nbsp;</h1><p style="text-align: center;"><b><i>Топ-5 пробок</i></b> в Новосибирске <span style="color:darkblue"><i>с 15 по 21 декабря 2014 года</i></span>:&nbsp;</p><ol><li id="c_oic8">Пробка в 12,8 км - <i>17 декабря</i>,&nbsp;</li><li id="c_oic8"><b></b> - Бердское шоссе,&nbsp;</li><li id="c_oic8">Большевистская улица - от Старого шоссе до <span style="color:red">Красного проспекта</span> - <b>3 часа 10 минут</b>.</li></ol></div>' },
			{ "event_type" : "N", "event_startDate" : "2015-12-17", "event_startTime" : "15:10", "event_duration" : "30", "event_result" : "Из-за приближающегося Нового года выросло количество машин на дорогах в выходные. Пробки в субботу составили 6 баллов, в воскресенье – 3 балла. Это выше, чем обычно. Топ-5 пробок в Новосибирске с 15 по 21 декабря 2014 года: Пробка в 12,8 км Бердское шоссе, Большевистская улица - от Старого шоссе до Красного проспекта. " },
			{ "event_type" : "N", "event_startDate" : "2015-12-17", "event_startTime" : "03:10", "event_duration" : "30", "event_result" : "Из-за приближающегося Нового года выросло количество машин на дорогах в выходные. Пробки в субботу составили 6 баллов, в воскресенье – 3 балла. Это выше, чем обычно. Топ-5 пробок в Новосибирске с 15 по 21 декабря 2014 года: Пробка в 12,8 км Бердское шоссе, Большевистская улица - от Старого шоссе до Красного проспекта." }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-28" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Старт <span style=\"color:red\">торжественным открытиям елочных площадок</span> в Советском районе дадут&nbsp;</h1><ol><li id=\"c_8ru4\"><b>20 декабря</b>&nbsp;</li><li id=\"c_8ru4\">в <b>11.00</b>&nbsp;</li><li id=\"c_8ru4\">у <b><i>Агропромпарка \'Казань</i></b> (ул.Аграрная, 2).&nbsp;</li></ol><ul><li id=\"c_2bhb\"><b>22 декабря</b>&nbsp;</li><li id=\"c_2bhb\">в <b>16.00</b> зажгутся огни на елке&nbsp;</li><li id=\"c_2bhb\">в <i>микрорайоне&nbsp;</i><b>\'Азино-2\'</b> по ул.Минская, 22.</li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-20", "event_startTime" : "11:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Старт <span style="color:red">торжественным открытиям елочных площадок</span> в Советском районе дадут&nbsp;</h1><ol><li id="c_8ru4"><b></b>&nbsp;</li><li id="c_8ru4">в <b></b>&nbsp;</li><li id="c_8ru4">у <b><i>Агропромпарка \'Казань</i></b> (ул.Аграрная, 2).&nbsp;</li></ol><ul><li id="c_2bhb"><b>22 декабря</b>&nbsp;</li><li id="c_2bhb">в <b>16.00</b> зажгутся огни на елке&nbsp;</li><li id="c_2bhb">в <i>микрорайоне&nbsp;</i><b>\'Азино-2\'</b> по ул.Минская, 22.</li></ul></div>'            },
			{ "event_type" : "N", "event_startDate" : "2015-12-20", "event_startTime" : "23:00", "event_duration" : "30", "event_result" : "Старт торжественным открытиям елочных площадок в Советском районе дадут у Агропромпарка 'Казань (ул.Аграрная, 2). 22 декабря в 16.00 зажгутся огни на елке в микрорайоне 'Азино-2' по ул.Минская, 22."            },
			{ "event_type" : "N", "event_startDate" : "2015-12-20",                              "event_duration" : "30", "event_result" : "Старт торжественным открытиям елочных площадок в Советском районе дадут в 11.00 у Агропромпарка 'Казань (ул.Аграрная, 2). 22 декабря в 16.00 зажгутся огни на елке в микрорайоне 'Азино-2' по ул.Минская, 22."    },
			{ "event_type" : "N",                                                    "event_startTime" : "11:00", "event_duration" : "30", "event_result" : "Старт торжественным открытиям елочных площадок в Советском районе дадут 20 декабря у Агропромпарка 'Казань (ул.Аграрная, 2). 22 декабря в 16.00 зажгутся огни на елке в микрорайоне 'Азино-2' по ул.Минская, 22." },
			{ "event_type" : "N",                                                    "event_startTime" : "23:00", "event_duration" : "30", "event_result" : "Старт торжественным открытиям елочных площадок в Советском районе дадут 20 декабря у Агропромпарка 'Казань (ул.Аграрная, 2). 22 декабря в 16.00 зажгутся огни на елке в микрорайоне 'Азино-2' по ул.Минская, 22." }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-29" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ol><li id=\"c_bxp2\"><b>29 дек</b> мес&nbsp;</li><li id=\"c_bxp2\">в <b>19:30</b>&nbsp;</li><li id=\"c_bxp2\">примерно <i>на 3 часа</i>&nbsp;</li></ol><p style=\"text-align: justify;\"><span style=\"color:red\"><b>Торжественное мероприятие</b></span> по случаю закладки двух кабельных судов <i>проекта 15310</i> на<i style=\"font-weight: bold;\"> ОАО \'Зеленодольский завод им.А.М.Горького\'.&nbsp;</i></p><p style=\"text-align: center;\"><i>Принимают участие</i>&nbsp;</p><ul class=\"checkbox\"><li id=\"c_qjqo\"><i>заместитель Министра обороны</i> Российской Федерации <b><i>Юрий Иванович Борисов&nbsp;</i></b></li><li id=\"c_65bd\">и <i>Премьер-министр</i> Республики Татарстан<b><i> И.Ш.Халиков</i></b></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-29", "event_startTime" : "19:30", "event_duration" : "180", "event_result" : '<div id="at_content" contenteditable="true"><ol><li id="c_bxp2"><b></b> мес&nbsp;</li><li id="c_bxp2">в <b></b>&nbsp;</li><li id="c_bxp2">примерно <i></i>&nbsp;</li></ol><p style="text-align: justify;"><span style="color:red"><b>Торжественное мероприятие</b></span> по случаю закладки двух кабельных судов <i>проекта 15310</i> на<i style="font-weight: bold;"> ОАО \'Зеленодольский завод им.А.М.Горького\'.&nbsp;</i></p><p style="text-align: center;"><i>Принимают участие</i>&nbsp;</p><ul class="checkbox"><li id="c_qjqo"><i>заместитель Министра обороны</i> Российской Федерации <b><i>Юрий Иванович Борисов&nbsp;</i></b></li><li id="c_65bd">и <i>Премьер-министр</i> Республики Татарстан<b><i> И.Ш.Халиков</i></b></li></ul></div>'                       },
			{ "event_type" : "N", "event_startDate" : "2015-12-29", "event_startTime" : "19:30", "event_duration" : "30",  "event_result" : "примерно на 3 часа Торжественное мероприятие по случаю закладки двух кабельных судов проекта 15310 на ОАО 'Зеленодольский завод им.А.М.Горького'. Принимают участие заместитель Министра обороны Российской Федерации Юрий Иванович Борисов и Премьер-министр Республики Татарстан И.Ш.Халиков"             },
			{ "event_type" : "N", "event_startDate" : "2015-12-29",                              "event_duration" : "180", "event_result" : "в 19:30 примерно Торжественное мероприятие по случаю закладки двух кабельных судов проекта 15310 на ОАО 'Зеленодольский завод им.А.М.Горького'. Принимают участие заместитель Министра обороны Российской Федерации Юрий Иванович Борисов и Премьер-министр Республики Татарстан И.Ш.Халиков"               },
			{ "event_type" : "N",                                                    "event_startTime" : "19:30", "event_duration" : "180", "event_result" : "29 дек мес примерно Торжественное мероприятие по случаю закладки двух кабельных судов проекта 15310 на ОАО 'Зеленодольский завод им.А.М.Горького'. Принимают участие заместитель Министра обороны Российской Федерации Юрий Иванович Борисов и Премьер-министр Республики Татарстан И.Ш.Халиков"            },
			{ "event_type" : "N",                                                    "event_startTime" : "19:30", "event_duration" : "30",  "event_result" : "29 дек мес примерно на 3 часа Торжественное мероприятие по случаю закладки двух кабельных судов проекта 15310 на ОАО 'Зеленодольский завод им.А.М.Горького'. Принимают участие заместитель Министра обороны Российской Федерации Юрий Иванович Борисов и Премьер-министр Республики Татарстан И.Ш.Халиков"  },
			{ "event_type" : "N", "event_startDate" : "2015-12-29",                              "event_duration" : "30",  "event_result" : "мес в 19:30 примерно на 3 часа Торжественное мероприятие по случаю закладки двух кабельных судов проекта 15310 на ОАО 'Зеленодольский завод им.А.М.Горького'. Принимают участие заместитель Министра обороны Российской Федерации Юрий Иванович Борисов и Премьер-министр Республики Татарстан И.Ш.Халиков" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-30" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>17 числа декабрь месяца&nbsp;</h1><p style=\"text-align: justify;\"><b><i>Элитный </i></b>(второй отборочный) раунд <span style=\"color:red\"><i>Чемпионата Европы</i></span> по футболу <b>2015 </b>года среди юношеских сборных команд до 17 лет,&nbsp;</p><ul><li id=\"c_0xa2\"><b>17 – 31 декабря</b> стадион \'Рубин\'.</li><li id=\"c_0xa2\">Начало <b>в 17</b></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-17", "event_startTime" : "17:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>&nbsp;</h1><p style="text-align: justify;"><b><i>Элитный </i></b>(второй отборочный) раунд <span style="color:red"><i>Чемпионата Европы</i></span> по футболу <b>2015 </b>года среди юношеских сборных команд до 17 лет,&nbsp;</p><ul><li id="c_0xa2"><b>17 – 31 декабря</b> стадион \'Рубин\'.</li><li id="c_0xa2">Начало <b></b></li></ul></div>'                          },
			{ "event_type" : "N", "event_startDate" : "2015-12-17",                              "event_duration" : "30", "event_result" : "Элитный (второй отборочный) раунд Чемпионата Европы по футболу 2015 года среди юношеских сборных команд до 17 лет, 17 – 31 декабря стадион 'Рубин'.Начало в 17"                      },
			{ "event_type" : "N",                                                    "event_startTime" : "17:00", "event_duration" : "30", "event_result" : "17 числа декабрь месяца Элитный (второй отборочный) раунд Чемпионата Европы по футболу 2015 года среди юношеских сборных команд до 17 лет, 17 – 31 декабря стадион 'Рубин'. Начало" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-31" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>в декабре, 03&nbsp;</h1><p style=\"text-align: justify;\">открывается <span style=\"color:red\">Республиканская профильная смена</span> <b><i>\'Галстучная страна\'&nbsp;</i></b></p><ul><li id=\"c_g97g\"><i>продолжительностью</i> <b>03-09 декабря</b>.&nbsp;</li><li id=\"c_g6oi\"><i>Открытие </i>состоится <b>в 00:00</b><br></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-03", "event_startTime" : "00:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1> nbsp;</h1><p style="text-align: justify;">открывается <span style="color:red">Республиканская профильная смена</span> <b><i>\'Галстучная страна\'&nbsp;</i></b></p><ul><li id="c_g97g"><i>продолжительностью</i> <b>03-09 декабря</b>.&nbsp;</li><li id="c_g6oi"><i>Открытие </i>состоится <b></b><br></li></ul></div>'               },
			{ "event_type" : "N", "event_startDate" : "2015-12-03",                              "event_duration" : "30", "event_result" : "открывается Республиканская профильная смена 'Галстучная страна' продолжительностью 03-09 декабря. Открытие состоится в 00:00"       },
			{ "event_type" : "N",                                                   "event_startTime" : "00:00", "event_duration" : "30", "event_result" : "в декабре, 03 открывается Республиканская профильная смена 'Галстучная страна' продолжительностью 03-09 декабря. Открытие состоится" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-32" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><p style=\"text-align: center;\">Заседание коллегии <span style=\"color:red\"><b><i>Прокуратуры Республики Татарстан</i></b></span>&nbsp;</p><h1><span style=\"color:green\">'О подведении итогов работы Прокуратуры Республики Татарстан за 2014 год'</span>&nbsp;</h1><ul class=\"checkbox\"><li id=\"c_52u4\">состоится <b>23 декабря</b>я&nbsp;</li><li id=\"c_kjrk\"><i>в 10:00</i> .\n</li></ul><ul><li id=\"c_2te9\"><b><i>Адрес</i></b> г.Казань, ул.Кремлевская, д.14&nbsp;</li><li id=\"c_2te9\">тел. <i>12-345-67</i></li></ul></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-23", "event_startTime" : "10:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><p style="text-align: center;">Заседание коллегии <span style="color:red"><b><i>Прокуратуры Республики Татарстан</i></b></span>&nbsp;</p><h1><span style="color:green">\'О подведении итогов работы Прокуратуры Республики Татарстан за 2014 год\'</span>&nbsp;</h1><ul class="checkbox"><li id="c_52u4">состоится <b></b>я&nbsp;</li><li id="c_kjrk"><i></i> .\n</li></ul><ul><li id="c_2te9"><b><i>Адрес</i></b> г.Казань, ул.Кремлевская, д.14&nbsp;</li><li id="c_2te9">тел. <i>12-345-67</i></li></ul></div>'            },
			{ "event_type" : "N", "event_startDate" : "2015-12-23",                              "event_duration" : "30", "event_result" : "Заседание коллегии Прокуратуры Республики Татарстан 'О подведении итогов работы Прокуратуры Республики Татарстан за 2014 год' состоится в 10:00 .\nАдрес г.Казань, ул.Кремлевская, д.14 тел. 12-345-67"    },
			{ "event_type" : "N",                                                    "event_startTime" : "10:00", "event_duration" : "30", "event_result" : "Заседание коллегии Прокуратуры Республики Татарстан 'О подведении итогов работы Прокуратуры Республики Татарстан за 2014 год' состоится 23 декабря .\nАдрес г.Казань, ул.Кремлевская, д.14 тел. 12-345-67" }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-33" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul><li id=\"c_64sh\"><i>06 дек. 2015</i>&nbsp;</li><li id=\"c_64sh\">в <b>16:00&nbsp;</b></li></ul><h1><span style=\"color:red\">Итоговое совещание структурных подразделений Федерального государственного учреждения</span>&nbsp;</h1><ol><li id=\"c_kmgu\">'Главное бюро <i>медико-социальной экспертизы</i> по Республике Татарстан'</li><li id=\"c_kmgu\">'О работе Федерального <i>государственного учреждения</i>&nbsp;</li><li id=\"c_kmgu\">'Главное бюро <i>медико-социальной экспертизы</i> по Республике Татарстан'&nbsp;</li><li id=\"c_kmgu\">в 2014 году и задачах на 2015 год',&nbsp;</li></ol><p style=\"text-align: right;\">г.Казань, ул. Бондаренко, д. 3&nbsp;</p><p style=\"text-align: right;\"><i>Напомнить за 4 часа</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-12-06", "event_startTime" : "16:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ul><li id="c_64sh"><i></i>&nbsp;</li><li id="c_64sh"> <b>&nbsp;</b></li></ul><h1><span style="color:red">Итоговое совещание структурных подразделений Федерального государственного учреждения</span>&nbsp;</h1><ol><li id="c_kmgu">\'Главное бюро <i>медико-социальной экспертизы</i> по Республике Татарстан\'</li><li id="c_kmgu">\'О работе Федерального <i>государственного учреждения</i>&nbsp;</li><li id="c_kmgu">\'Главное бюро <i>медико-социальной экспертизы</i> по Республике Татарстан\'&nbsp;</li><li id="c_kmgu">в 2014 году и задачах на 2015 год\',&nbsp;</li></ol><p style="text-align: right;">г.Казань, ул. Бондаренко, д. 3&nbsp;</p><p style="text-align: right;"><i></i></p></div>'                                  , "event_alarms" : "-240" },
			{ "event_type" : "N", "event_startDate" : "2015-12-06",                              "event_duration" : "30", "event_result" : "в 16:00 Итоговое совещание структурных подразделений Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' 'О работе Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' в 2014 году и задачах на 2015 год', г.Казань, ул. Бондаренко, д. 3"                          },
			{ "event_type" : "N",                                   "event_startTime" : "16:00", "event_duration" : "30", "event_result" : "06 дек. 2015 Итоговое совещание структурных подразделений Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' 'О работе Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' в 2014 году и задачах на 2015 год', г.Казань, ул. Бондаренко, д. 3"                     },
			{ "event_type" : "N", "event_startDate" : "2015-12-06",                              "event_duration" : "30", "event_result" : "в 16:00 Итоговое совещание структурных подразделений Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' 'О работе Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' в 2014 году и задачах на 2015 год', г.Казань, ул. Бондаренко, д. 3 Напомнить за 4 часа"      },
			{ "event_type" : "N",                                   "event_startTime" : "16:00", "event_duration" : "30", "event_result" : "06 дек. 2015 Итоговое совещание структурных подразделений Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' 'О работе Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' в 2014 году и задачах на 2015 год', г.Казань, ул. Бондаренко, д. 3 Напомнить за 4 часа" },
			{ "event_type" : "N", "event_startDate" : "2015-12-06", "event_startTime" : "16:00", "event_duration" : "30", "event_result" : "Итоговое совещание структурных подразделений Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' 'О работе Федерального государственного учреждения 'Главное бюро медико-социальной экспертизы по Республике Татарстан' в 2014 году и задачах на 2015 год', г.Казань, ул. Бондаренко, д. 3 Напомнить за 4 часа"              }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-34" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><ul class=\"checkbox\"><li id=\"c_ffwz\">1 сентября&nbsp;</li><li id=\"c_s9p9\">в 9 часов утра&nbsp;</li></ul><p style=\"text-align: center;\">состоится <span style=\"color:red\"><b><i>торжественная линейка</i></b></span>, посвященная&nbsp;</p><h1>Первому учебному дню для первоклассников и их родителей.&nbsp;</h1><p style=\"text-align: justify;\"><br></p><p style=\"text-align: justify;\">После линейки будет происходить <b>распределение по классам</b>:\n</p><ol><li id=\"c_j2nc\"><b>1 а</b> - 20 чел,&nbsp;<i>каб 5&nbsp;</i></li><li id=\"c_j2nc\"><b>1 б</b> - 16 чел,<i> каб 9</i>&nbsp;</li><li id=\"c_j2nc\"><b>1 в</b> - 17 чел, <i>каб 11</i></li></ol></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-09-01", "event_startTime" : "09:00", "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><ul class="checkbox"><li id="c_ffwz">&nbsp;</li><li id="c_s9p9"> nbsp;</li></ul><p style="text-align: center;">состоится <span style="color:red"><b><i>торжественная линейка</i></b></span>, посвященная&nbsp;</p><h1>Первому учебному дню для первоклассников и их родителей.&nbsp;</h1><p style="text-align: justify;"><br></p><p style="text-align: justify;">После линейки будет происходить <b>распределение по классам</b>:\n</p><ol><li id="c_j2nc"><b>1 а</b> - 20 чел,&nbsp;<i>каб 5&nbsp;</i></li><li id="c_j2nc"><b>1 б</b> - 16 чел,<i> каб 9</i>&nbsp;</li><li id="c_j2nc"><b>1 в</b> - 17 чел, <i>каб 11</i></li></ol></div>'                },
			{ "event_type" : "N", "event_startDate" : "2015-09-01", "event_startTime" : "21:00", "event_duration" : "30", "event_result" : "утра состоится торжественная линейка, посвященная Первому учебному дню для первоклассников и их родителей. После линейки будет происходить распределение по классам:\n1 а - 20 чел, каб 5 1 б - 16 чел, каб 9 1 в - 17 чел, каб 11"           },
			{ "event_type" : "N", "event_startDate" : "2015-09-01",                              "event_duration" : "30", "event_result" : "в 9 часов утра состоится торжественная линейка, посвященная Первому учебному дню для первоклассников и их родителей. После линейки будет происходить распределение по классам:\n1 а - 20 чел, каб 5 1 б - 16 чел, каб 9 1 в - 17 чел, каб 11" },
			{ "event_type" : "N",                                                  "event_startTime" : "09:00", "event_duration" : "30", "event_result" : "1 сентября состоится торжественная линейка, посвященная Первому учебному дню для первоклассников и их родителей. После линейки будет происходить распределение по классам:\n1 а - 20 чел, каб 5 1 б - 16 чел, каб 9 1 в - 17 чел, каб 11"     }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	},

	"TC-35" : {
		"origin" : "<div id=\"at_content\" contenteditable=\"true\"><h1>Крайний срок -&nbsp;</h1><ul><li id=\"c_noj2\">20 сент.&nbsp;</li><li id=\"c_cyhg\"><i>в 12:30</i>&nbsp;</li></ul><p><span style=\"color:red\"><b>Перечислить регулярный взнос</b></span> за пользование объектами водных биологических ресурсов за <i>август 2015 г</i>.&nbsp;</p><p><span style=\"color:green\">Пользователи водных биологических ресурсов</span> аполняют <b><i>платежное поручение</i></b> по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (<i>исключая внутренние водные объекты</i>):&nbsp;</p><ul class=\"checkbox\"><li id=\"c_w3ep\">18210704020011000110;&nbsp;</li><li id=\"c_0vr8\">ОКТМО;&nbsp;</li><li id=\"c_t13d\">ТП;&nbsp;</li><li id=\"c_c2me\">МС.01.2015;&nbsp;</li><li id=\"c_g1bl\">0;&nbsp;</li><li id=\"c_jwa6\">0;&nbsp;</li><li id=\"c_tmfr\">0&nbsp;</li></ul><p><b><i>сбор за пользование</i></b> объектами водных биологических ресурсов (по внутренним водным объектам):&nbsp;</p><ul><li id=\"c_6uno\">18210704030011000110;&nbsp;</li><li id=\"c_6uno\">ОКТМО;&nbsp;</li><li id=\"c_6uno\">ТП;&nbsp;</li><li id=\"c_6uno\">МС.01.2015;&nbsp;</li><li id=\"c_6uno\">0;&nbsp;</li><li id=\"c_6uno\">0;&nbsp;</li><li id=\"c_6uno\">0&nbsp;</li></ul><p style=\"text-align: right;\"><i>напомнить за 2 часа.</i></p></div>",
		"expectations" : [
			{ "event_type" : "N", "event_startDate" : "2015-09-20", "event_startTime" : "12:30",                      "event_duration" : "30", "event_result" : '<div id="at_content" contenteditable="true"><h1>Крайний срок -&nbsp;</h1><ul><li id="c_noj2">&nbsp;</li><li id="c_cyhg"><i></i>&nbsp;</li></ul><p><span style="color:red"><b>Перечислить регулярный взнос</b></span> за пользование объектами водных биологических ресурсов за <i>август 2015 г</i>.&nbsp;</p><p><span style="color:green">Пользователи водных биологических ресурсов</span> аполняют <b><i>платежное поручение</i></b> по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (<i>исключая внутренние водные объекты</i>):&nbsp;</p><ul class="checkbox"><li id="c_w3ep">18210704020011000110;&nbsp;</li><li id="c_0vr8">ОКТМО;&nbsp;</li><li id="c_t13d">ТП;&nbsp;</li><li id="c_c2me">МС.01.2015;&nbsp;</li><li id="c_g1bl">0;&nbsp;</li><li id="c_jwa6">0;&nbsp;</li><li id="c_tmfr">0&nbsp;</li></ul><p><b><i>сбор за пользование</i></b> объектами водных биологических ресурсов (по внутренним водным объектам):&nbsp;</p><ul><li id="c_6uno">18210704030011000110;&nbsp;</li><li id="c_6uno">ОКТМО;&nbsp;</li><li id="c_6uno">ТП;&nbsp;</li><li id="c_6uno">МС.01.2015;&nbsp;</li><li id="c_6uno">0;&nbsp;</li><li id="c_6uno">0;&nbsp;</li><li id="c_6uno">0&nbsp;</li></ul><p style="text-align: right;"><i>.</i></p></div>'                               , "event_alarms" : "-120"},
			{ "event_type" : "N", "event_startDate" : "2015-09-20", "event_startTime" : "00:30",                      "event_duration" : "30", "event_result" : "Крайний срок Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 сбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0"                               },
			{ "event_type" : "N", "event_startDate" : "2015-09-20",                                                   "event_duration" : "30", "event_result" : "Крайний срок - в 12:30 Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 сбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0."                      },
			{ "event_type" : "N",                                                   "event_startTime" : "12:30",                      "event_duration" : "30", "event_result" : "Крайний срок - 20 сент. Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0\tсбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0."                    },
			{ "event_type" : "N",                                                   "event_startTime" : "00:30",                      "event_duration" : "30", "event_result" : "Крайний срок - 20 сент. Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0\tсбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0."                    },
			{ "event_type" : "N", "event_startDate" : "2015-09-20", "event_startTime" : "12:30",                      "event_duration" : "30", "event_result" : "Крайний срок - Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 сбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 напомнить за 2 часа"           },
			{ "event_type" : "N", "event_startDate" : "2015-09-20", "event_startTime" : "00:30",                      "event_duration" : "30", "event_result" : "Крайний срок - Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 сбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 напомнить за 2 часа"           },
			{ "event_type" : "N", "event_startDate" : "2015-09-20",                                                   "event_duration" : "30", "event_result" : "Крайний срок - в 12:30 Перечислить регулярный взнос за пользование объектами водных биологических ресурсов за август 2015 г.Пользователи водных биологических ресурсов аполняют платежное поручение по таким реквизитам:\nсбор за пользование объектами водных биологических ресурсов (исключая внутренние водные объекты): 18210704020011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 сбор за пользование объектами водных биологических ресурсов (по внутренним водным объектам): 18210704030011000110; ОКТМО; ТП; МС.01.2015; 0; 0; 0 напомнить за 2 часа"   }
		],
		"environment" : { "time" : "09:00", "date" : "2015-03-13" , "workTime" : { "Mo" : "09:00-19:00", "Tu" : "09:00-19:00", "We" : "09:00-19:00", "Th" : "09:00-19:00", "Fr" : "09:00-19:00", "Sa" : "09:00-13:00", "Su" : "09:00-13:00" } }
	}
};
